<?php echo process_template('admin_header');?>
<h2>Edit carrier:</h2>
<form action="admin.php" method="post">
<dl>
<dt></dt>
<dd><input type="hidden" name="action" value="edit_carrier_submit" /><input type="hidden" name="id" value="<?php echo $var_carrierInfo['id'];?>" /></dd>
<dt><label>Carrier: </label></dt><dd><input type="text" name="carrier" id="carrier" value="<?php echo $var_carrierInfo['carrier'];?>"/></dd>
<dt><label>Description: </label></dt><dd><textarea name="description" id="description"cols="15" rows="5"><?php echo $var_carrierInfo['description'];?></textarea></dd>
<dt><label>Redirect URL: </label></dt><dd><input type="text" name="redirect_url" id="redirect_url" value="<?php echo $var_carrierInfo['redirect_url'];?>"/></dd>
<dt></dt><dd><input type="submit" value="Edit" /></dd>
</dl>
</form>
<?php echo process_template('admin_footer');?>
